// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2KdQ5vy7QV0uV3Calt_G3X4ndb38wspw',
    appId: '1:548768469582:web:6b598c58c236b9fd66e91f',
    messagingSenderId: '548768469582',
    projectId: 'fir-genui-d15e6',
    authDomain: 'fir-genui-d15e6.firebaseapp.com',
    storageBucket: 'fir-genui-d15e6.firebasestorage.app',
    measurementId: 'G-WFP67TTBEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIFJ7_ivVlssKbViGBpUhilbWVMPb1FJw',
    appId: '1:548768469582:android:8c567b50f9f59f8a66e91f',
    messagingSenderId: '548768469582',
    projectId: 'fir-genui-d15e6',
    storageBucket: 'fir-genui-d15e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQfASJ1Ckc93iMNiTx8YD1iKOGRhyBwzY',
    appId: '1:548768469582:ios:0e2682da16a51bc866e91f',
    messagingSenderId: '548768469582',
    projectId: 'fir-genui-d15e6',
    storageBucket: 'fir-genui-d15e6.firebasestorage.app',
    iosBundleId: 'com.example.genuiDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQfASJ1Ckc93iMNiTx8YD1iKOGRhyBwzY',
    appId: '1:548768469582:ios:0e2682da16a51bc866e91f',
    messagingSenderId: '548768469582',
    projectId: 'fir-genui-d15e6',
    storageBucket: 'fir-genui-d15e6.firebasestorage.app',
    iosBundleId: 'com.example.genuiDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2KdQ5vy7QV0uV3Calt_G3X4ndb38wspw',
    appId: '1:548768469582:web:bda444e17b27092066e91f',
    messagingSenderId: '548768469582',
    projectId: 'fir-genui-d15e6',
    authDomain: 'fir-genui-d15e6.firebaseapp.com',
    storageBucket: 'fir-genui-d15e6.firebasestorage.app',
    measurementId: 'G-HJ62YFC22P',
  );
}
